services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.custom
    container_name: codechat-rc-9
    restart: unless-stopped
    volumes:
      - instances_connecteds:/codechat/instances
    env_file:
      - .env
    entrypoint: sh -c "npx prisma generate && npx prisma migrate deploy && node ./dist/src/main"
    networks:
      - public-network

volumes:
  instances_connecteds:
  
networks:
  public-network:
    external: true
    name: easypanel